const {
  AD_SERVICE_ADDR = "",
  CART_SERVICE_ADDR = "",
  CHECKOUT_SERVICE_ADDR = "",
  CURRENCY_SERVICE_ADDR = "",
  PRODUCT_CATALOG_SERVICE_ADDR = "",
  RECOMMENDATION_SERVICE_ADDR = "",
  SHIPPING_SERVICE_ADDR = "",
  ENV_PLATFORM = "",
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "",
  OTEL_SERVICE_NAME = "frontend",
  PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "",
} = process.env;

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    instrumentationHook: true,
  },
  env: {
    AD_SERVICE_ADDR,
    CART_SERVICE_ADDR,
    CHECKOUT_SERVICE_ADDR,
    CURRENCY_SERVICE_ADDR,
    PRODUCT_CATALOG_SERVICE_ADDR,
    RECOMMENDATION_SERVICE_ADDR,
    SHIPPING_SERVICE_ADDR,
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
    NEXT_PUBLIC_PLATFORM: ENV_PLATFORM,
    NEXT_PUBLIC_OTEL_SERVICE_NAME: OTEL_SERVICE_NAME,
    NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:
      PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
  },
};

export default nextConfig;
